name: "Sandbox"

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        type: "string"

jobs:
  create:
    name: "Create sandbox"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Echo"
        run: "echo title: ${{ inputs.title }}"
